### ISSUE TITLE
Generate Vectors

### ISSUE THREAD

**Issue by ijyliu** [ijyliu/data-engineering-project#2]
## Documents/Data

https://www.kaggle.com/datasets/sonu1607/tosdr-terms-of-service-corpus

Updated March 14, 2023

## Tasks

- [x] Get documents (tosdr)
- [x] Convert to ASCII
- [x] Sentence tokenize
- [x] Insert company name at the front of every sentence (company name can be read in from the filename). 
- [x] Run through Mixedbread embedding model

**Comment by ijyliu** [comment]
https://python.langchain.com/docs/integrations/vectorstores/milvus

**Comment by ijyliu** [comment]
Document corpus from: https://www.kaggle.com/datasets/sonu1607/tosdr-terms-of-service-corpus

**Comment by ijyliu** [comment]
LLM to hook the RAG up to: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2

**Comment by ijyliu** [comment]
Milvus RAG tutorial: https://github.com/towhee-io/examples/blob/main/nlp/question_answering/1_build_question_answering_engine.ipynb

**Comment by ijyliu** [comment]
mixedbread embeddings now available
